### ISSUE TITLE
No matching SRT file found, even though it's there

### ISSUE THREAD

**Issue by noeldtz** [ChrisHansenTech/PlexSubSync#5]
hi! 

Great work making this, it looks really promising. 
I have managed to set it up. However when i try to sync subtitles, it cannot find a matching .SRT file, even though the file is there and the naming is correct (as far as i can see). 

I setup the integration through docker.compose: 

```
services:
  subsyncforplex:
    image: ghcr.io/chrishansentech/subsyncforplex:latest
    container_name: subsyncforplex
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /mnt/md0/multimedia/media:/media
    environment:
      - PLEX_TOKEN=XXXX
      - PLEX_URL=http://192.168.2.46:32400
      - DEFAULT_AUDIO_LANG=en
      - DEFAULT_SUB_LANG=nl
      - HOME_ASSISTANT_WEBHOOK_URL=http://192.168.2.46:8123/api/webhook/subsync
    network_mode: host
```

and i use this to get the media ID of the currently playing track:

```
sensor:
  - platform: rest
    scan_interval: 30
    resource: "http://172.18.0.1:32400/status/sessions?X-Plex-Token=XXXX"
    method: GET
    name: plex_sessions
    value_template: "{{ value_json.MediaContainer.size }}"
    json_attributes:
      - MediaContainer
      - Metadata
    headers:
      Accept: application/json
```

```
template:
  - sensor:
      - name: "Currently Playing Plex Metadata ID"
        state: >
          {% if state_attr('sensor.plex_sessions', 'MediaContainer') and state_attr('sensor.plex_sessions', 'MediaContainer').Metadata %}
            {{ state_attr('sensor.plex_sessions', 'MediaContainer').Metadata[0].ratingKey }}
          {% else %}
            None
          {% endif %}
```

and finally i use this to request a subtitle sync:

  ```
subsyncforplex_en:
    url: "http://192.168.2.46:8000/subsync"
    method: POST
    content_type: "application/json"
    payload: >
      {
        "media_id": "{{ states('sensor.currently_playing_plex_metadata_id') }}",
        "entity_id": "{{ trigger.entity_id if trigger is defined else 'none' }}",
        "sub_lang": "en"

      }
  subsyncforplex_nl:
    url: "http://192.168.2.46:8000/subsync"
    method: POST
    content_type: "application/json"
    payload: >
      {
        "media_id": "{{ states('sensor.currently_playing_plex_metadata_id') }}",
        "entity_id": "{{ trigger.entity_id if trigger is defined else 'none' }}",
        "sub_lang": "nl"
      }

```
en example of the path of an episode i have tried to sync is the following:

/Volumes/home-server/multimedia/media/TV shows/The Crown (2016) {imdb-tt4786824}/Season 01/The Crown (2016) - S01E03 - Windsor [Bluray-1080p][DTS-HD MA 5.1][h264]-PiR8.en.srt
/Volumes/home-server/multimedia/media/TV shows/The Crown (2016) {imdb-tt4786824}/Season 01/The Crown (2016) - S01E03 - Windsor [Bluray-1080p][DTS-HD MA 5.1][h264]-PiR8.mkv

This returns the following message to home assistant: SubSync failed for Windsor. Reason: No matching SRT file found. 

when i check the path of the mediafile using the python plex API i get the following:
/TV Shows/The Crown (2016) {imdb-tt4786824}/Season 01/The Crown (2016) - S01E03 - Windsor [Bluray-1080p][DTS-HD MA 5.1][h264]-PiR8.mkv

I don't really see what I'm missing here, hopefully you can help me!

Thanks!!
